trigger:
- main

jobs:
  job: gradle
  pool:
    image: ubuntu-latest
  steps:
  - displayName: install dictzip command
    bash: sudo apt-get install -y dictzip
  - task: Gradle@2
    inputs:
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      tasks: 'check'
## when library project to publish to OSSRH
#  - task: Gradle@2
#    displayName: Publish package to OSSRH
#    inputs:
#      javaHomeOption: 'JDKVersion'
#      jdkVersionOption: '1.8'
#      tasks: 'publishToSonatype'
#    env:
#      ORG_GRADLE_PROJECT_signingKey: $( secrets_GPG_SECRET_KEY )
#      ORG_GRADLE_PROJECT_signingPassword: $( secrets_GPG_KEY_PASSPHARASE )
#      SONATYPE_USER: $( secrets_SONATYPE_USER )
#      SONATYPE_PASS: $( secrets_SONATYPE_PASS )
