plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
    id 'com.gradle.develocity' version '4.0.2'
}

def isCI = "true".equals(System.getProperty('envIsCi'))

develocity {
    buildScan {
        buildScan.uploadInBackground = !isCI
        termsOfUseUrl = "https://gradle.com/terms-of-service"
        termsOfUseAgree = "yes"
    }
}
rootProject.name = 'dictzip'
include 'northside-io', 'dictzip-lib', 'dictzip-cli'
