plugins {
    id 'java-library'
    id 'jacoco'
    id 'checkstyle'
    id 'signing'
    id 'maven-publish'
}

version = rootProject.version

repositories {
    mavenCentral()
}

dependencies {
    implementation(libs.jspecify)
    testImplementation(libs.junit.jupiter)
    testImplementation(libs.commons.io)
    testImplementation project(':northside-io')
}

test {
    useJUnitPlatform()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(11)
    }
    withSourcesJar()
    withJavadocJar()
}

javadoc {
    options.locale = 'en_US'
}

artifacts {
    archives jar
    archives sourcesJar
    archives javadocJar
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
            artifactId = 'dictzip'
            groupId = 'tokyo.northside'
            pom {
                name.set("dictzip")
                description.set(projectDesc)
                url.set(projectUrl)
                licenses {
                    license {
                        name.set("GNU General Public License v2.0 w/Classpath exception")
                        url.set("https://www.gnu.org/software/classpath/license.html")
                    }
                }
                scm {
                    connection.set("scm:git:git://github.com/miurahr/dictzip-java.git")
                    developerConnection.set("scm:git:git://github.com/miurahr/dictzip-java.git")
                    url.set(projectUrl)
                }
                developers {
                    developer {
                        id.set("miurahr")
                        name.set("Hiroshi Miura")
                        email.set("miurahr@linux.com")
                    }
                }
                issueManagement {
                    url.set(projectUrl + "/issues")
                }
            }
        }
    }
}

signing {
    if (project.hasProperty("signingKey")) {
        def signingKey = findProperty("signingKey").toString()
        def signingPassword = findProperty("signingPassword").toString()
        useInMemoryPgpKeys(signingKey, signingPassword)
    } else {
        useGpgCmd()
    }
    sign publishing.publications.mavenJava
}

tasks.withType(Sign).configureEach {
    def hasKey = project.hasProperty("signingKey") || project.hasProperty("signing.gnupg.keyName")
    onlyIf { hasKey && !project.version.toString().endsWith("-SNAPSHOT")}
}

checkstyle {
    ignoreFailures = true
    toolVersion = libs.versions.checkstyle.get()
}
