[versions]
junit5 = "5.8.2"
commons_io = "2.16.1"
picocli = "4.7.5"
checkstyle = "8.41.1"
jspecify = "1.0.0"

[libraries]
junit-jupiter = {group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit5"}
commons-io = {group = "commons-io", name = "commons-io", version.ref = "commons_io"}
picocli = {group = "info.picocli", name = "picocli", version.ref = "picocli"}
jspecify = {group = "org.jspecify", name = "jspecify", version.ref = "jspecify"}

[plugins]
spotbugs = {id = "com.github.spotbugs", version = "6.0.14"}
spotless = {id = "com.diffplug.spotless", version = "6.25.0"}
git-version = {id = "com.palantir.git-version", version = "3.0.0"}
nexus-publish = {id = "io.github.gradle-nexus.publish-plugin", version = "2.0.0"}
