name: Check

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

      - name: Install dictzip
        run: sudo apt-get update && sudo apt-get install -y dictzip
        id: install-dictzip

      - uses: gradle/actions/setup-gradle@v6
        name: Setup Gradle
        id: setup-gradle

      - name: Run build check
        run: ./gradlew check --scan
        id: gradle-check
