name: Build and test

on: push

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build
    - uses: actions/upload-artifact@v1
      with:
        name: dictzip-libray
        path: dictzip-lib/build/libs/*.jar
    - uses: actions/upload-artifact@v1
      with:
        path: dictzip-cli/build/distributions/*
