name: Build and test

on: push

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v2.1.0
      with:
        distribution: 'adopt'
        java-version: 8.0.292+10
    - uses: eskatos/gradle-command-action@v1
      with:
        arguments: build distZip
      env:
        CI: true
    - name: comment PR
      uses: unsplash/comment-on-pr@master
      if: failure()
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: Build failed ${{ steps.gradle.outputs.build-scan-url }}
        check_for_duplicate_msg: true
    - uses: actions/upload-artifact@v2.2.3
      with:
        name: dictzip-library
        path: dictzip-lib/build/libs
    - uses: actions/upload-artifact@v2.2.3
      with:
        name: dictzip-cli
        path: dictzip-cli/build/distributions
