name: Gradle check

on: push

jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2.5.0
      with:
        distribution: 'temurin'
        java-version: '8'
    - name: install dictzip command
      run: sudo apt-get install -y dictzip
    - uses: gradle/gradle-build-action@v2
    - run: ./gradlew check
      env:
        CI: true
